### ISSUE TITLE
Original Features Roadmap

### ISSUE THREAD

**Issue by jabezborja** [jabezborja/tambayan#22]
Features to implement:
- [ ] Add Room Mod Moderation Tools
- [ ] Add User Profile Modal View
- [ ] Add `@mention` to Chat
- [ ] Add Emoji React to Chat message
- [ ] Add Emoji Picker to Chat

If you want to add more, please create a new Issue.
